### ISSUE TITLE
Melhoria consulta nos repositórios com value objects

### ISSUE THREAD

**Issue by gabriellima09** [g12-4soat/tech-lanches#5]
Trazer todos os itens de uma tabela para a memória é uma má prática como acontece no código abaixo:

![image](https://github.com/g12-4soat/tech-lanches/assets/32204447/05461041-090f-4f55-9e41-08f6bf8eff88)

Precisamos resolver o problema de mapeamento de value objects.

_System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: The expression 'x => x.CPF.Numero' is not a valid member access expression. The expression should represent a simple property or field access: 't => t.MyProperty'. When specifying multiple properties or fields, use an anonymous type: 't => new { t.MyProperty, t.MyField }'. (Parameter 'memberAccessExpression')
   at Microsoft.EntityFrameworkCore.Infrastructure.ExpressionExtensions.GetMemberAccessList(LambdaExpression memberAccessExpression)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder1.HasIndex(Expression1 indexExpression)
   at TechLanches.Infrastructure.EntityTypeConfigurations.ClienteEntityTypeConfiguration.Configure(EntityTypeBuilder1 builder) in C:\projects\tech-lanches\src\TechLanches\TechLanches.Infrastructure\EntityTypeConfigurations\ClienteEntityTypeConfiguration.cs:line 62
   at Microsoft.EntityFrameworkCore.ModelBuilder.ApplyConfiguration[TEntity](IEntityTypeConfiguration1 configuration)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)_

**Comment by gabriellima09** [comment]
Foi possível resolver o problema e foi incluída a correção no PR #7 .

Vale ressaltar que na versão 8 do EF Core, o suporte para ValueObjects foi melhorado, logo um upgrade de versão do dotnet viria a ajudar: https://devblogs.microsoft.com/dotnet/announcing-ef8-rc1/
